# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-IODEF-PhraudReport
version:      0.01
version_from: lib/XML/IODEF/PhraudReport.pm
installdirs:  site
requires:
    XML::IODEF:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
